//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\jlips\Documents\Visual Studio 2017\Projects\antlr_test\antlr_test\json.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


	using antlr_test.Abstract;
	using antlr_test.Builders;

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="jsonParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IjsonListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="jsonParser.compileUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompileUnit([NotNull] jsonParser.CompileUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="jsonParser.compileUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompileUnit([NotNull] jsonParser.CompileUnitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="jsonParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] jsonParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="jsonParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] jsonParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="jsonParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObject([NotNull] jsonParser.ObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="jsonParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObject([NotNull] jsonParser.ObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="jsonParser.objectProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectProperty([NotNull] jsonParser.ObjectPropertyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="jsonParser.objectProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectProperty([NotNull] jsonParser.ObjectPropertyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="jsonParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray([NotNull] jsonParser.ArrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="jsonParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray([NotNull] jsonParser.ArrayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="jsonParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] jsonParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="jsonParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] jsonParser.LiteralContext context);
}
